### ISSUE TITLE
Install dependencies 

### ISSUE THREAD

**Issue by knkrth** [alephsecurity/firehorse#9]
Hi, Is the program still work on the devices that are mentioned on the https://alephsecurity.com/2018/01/22/qualcomm-edl-1/ Even with the latest android (9.x) on them?

Can the provide us the installation guide & dependencies to run this program on both linux & windows.

I got the the following error by,

```
$git clone https://github.com/alephsecurity/firehorse
$cd firehorse/host
$firehorse/host(master)# python firehorse.py -t ugglite target read_partition devinfo
INFO: Downloading partition devinfo to ugglite-devinfo-read.bin...
Traceback (most recent call last):
  File "firehorse.py", line 119, in <module>
    main()
  File "firehorse.py", line 113, in main
    cmds[name](args)
  File "/workspace/dev/firehorse/host/target.py", line 102, in do_cmd
    fw.Framework.read_partition(args[1])
  File "/workspace/dev/firehorse/host/fw.py", line 141, in read_partition
    Framework.firehose(xml)
  File "/workspace/dev/firehorse/host/fw.py", line 290, in firehose
    return Framework.firehosep("../tmp/temp.xml")
  File "/workspace/dev/firehorse/host/fw.py", line 338, in firehosep
    stdout=subprocess.PIPE, stdin=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Is there any dependencies needs to be installed inorder to make this work?
 
I'm trying to unlock the boot loader of the Xiaomi device which uses the `prog_emmc_firehose_8953_ddr.mbn` via EDL mode.

Any help would be appreciative.

**Comment by t5k6** [comment]
You are missing the part for configuring constants.py file.
Like this (as shown on readme)
```
COM = "COM17"
FH_LOADER = r"C:\Program Files (x86)\Qualcomm\QPST437\bin\fh_loader.exe"
SAHARA_SERVER = r"C:\Program Files (x86)\Qualcomm\QPST437\bin\QSaharaServer.exe" 
```
